### PR TITLE
Allow defining of variables for feedback

### PR DESCRIPTION
**Pull request by krzyc**

### CODE REVIEW

**Review by JeffreyDavidsz — COMMENTED** [review]
Why the trim?

**Review by JeffreyDavidsz — APPROVED** [review]
ah you removed it

**Review by JeffreyDavidsz — APPROVED** [review]

**Review by Julusian — CHANGES_REQUESTED** [review]
Im a bit confused by this change, as it doesnt look like the values are ever set for the variables other than when they are reset.

Is this to make the variables from the 'websocket_variable' feedback be exposed properly? If so then it would be better to look at `this.subscriptions` for the list of variables, and to add a call to `this.setVariableDefinitions` as part of the subscribe/unsubscribe callbacks of that feedback

**Comment by krzyc** [comment]
@Julusian Yes, this PR exposes variables system-wide (and reset them to empty string if requested). Reversing things sounds good to me. I need to check that out.

**Comment by krzyc** [comment]
@Julusian Now variable definitions are extracted from subscriptions. Thanks for this tip.

**Review by krzyc — COMMENTED** [review]
I do not see any changes in this request.

**Pull request merged**
